services:
  simple-library-mysql:
    image: mysql:latest
    container_name: simple-library-mysql
    environment:
      MYSQL_ROOT_PASSWORD: Password123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: